language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
  - "8"

before_script:
  - npm install -g istanbul coveralls
  - npm install -g mocha
  - npm install -g browserify 
  - npm install -g uglify-js
  - npm install -g codeclimate-test-reporter
  - npm install -g mocha-phantomjs
  - npm install

after_success:
  - make coveralls
script:
  - npm test
  - make test-cov
